services:
  - docker

language: python

python:
  - 3.7

cache: pip

install:
  - make docker.pull
  - make docker.build

script:
  - mkdir test_output
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "make quality"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make detect_missing_migrations"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make migrate"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make static"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "./wait-for-it.sh db:5432 -- make test"

after_success:
  - pip install -U codecov
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run app "coverage xml"
  - codecov --file test_output/coverage.xml

# TODO Follow steps at https://docs.travis-ci.com/user/environment-variables#encrypting-environment-variables
# to define the following environment variables:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
#deploy:
#  - provider: script
#    script: bash .travis/docker_push.sh
#    on:
#      branch: master
