# Generated by Django 2.2.6 on 2019-11-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_scraping', '0002_auto_20191112_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skiresort',
            name='created_on',
        ),
    ]
