# Generated by Django 2.2.6 on 2019-11-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scraping', '0003_remove_skiresort_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiresort',
            name='resort_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
