# Generated by Django 2.2.6 on 2019-11-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkiResort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=200, unique=True)),
                ('trails_open', models.IntegerField(default=0)),
                ('lifts_open', models.IntegerField(default=0)),
                ('acres_open', models.IntegerField(default=0)),
                ('terrain_percent', models.IntegerField(default=0)),
                ('total_trails', models.IntegerField(default=0)),
                ('total_lifts', models.IntegerField(default=0)),
                ('lifts_on_hold', models.IntegerField(default=0)),
                ('black_diamonds_open', models.IntegerField(default=0)),
                ('double_black_diamonds_open', models.IntegerField(default=0)),
                ('overnight_snowfall', models.IntegerField(default=0)),
                ('twenty_four_hour_snowfall', models.IntegerField(default=0)),
                ('forty_eight_hour_snowfall', models.IntegerField(default=0)),
                ('seven_day_snowfall', models.IntegerField(default=0)),
                ('base_depth', models.IntegerField(default=0)),
                ('current_season', models.IntegerField(default=0)),
            ],
        ),
    ]
