# Generated by Django 2.2.6 on 2019-11-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkiResort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(max_length=200, unique=True)),
                ('trails_open', models.IntegerField(default=0)),
                ('lifts_open', models.IntegerField(default=0)),
                ('acres_open', models.IntegerField(default=0)),
                ('terrain_percent', models.IntegerField(default=0)),
                ('total_trails', models.IntegerField(default=0)),
                ('total_lifts', models.IntegerField(default=0)),
            ],
        ),
    ]
